### PR TITLE
Fix typo in BistablePCCavity.ipynb

### PR DESCRIPTION
**Pull request by alec-flexcompute**

### CODE REVIEW

**Review by tomflexcompute — APPROVED** [review]
Thanks @alec-flexcompute . Feel free to merge.

**Comment by alec-flexcompute** [comment]
Hmm I don't think I have permissions to merge. Could I grab permissions, or could you merge?

**Comment by tomflexcompute** [comment]
Oh can @daquinteroflex grant Alec the permission? 

Also @alec-flexcompute could you merge it into develop branch instead?

**Comment by alec-flexcompute** [comment]
Ah, I already merged the change into develop. This was to update pre/2.6

**Comment by tomflexcompute** [comment]
> Ah, I already merged the change into develop. This was to update pre/2.6

Oh I see. I don't think it needs to update pre2.6 since there will be a merge between develop and pre2.6 before a release or pre-release anyway, if we follow the same procedure as before. Anyway I'll just merge this one for now.

**Comment by alec-flexcompute** [comment]
Sounds good, thanks!

**Comment by daquinteroflex** [comment]
Permission granted for the future!

**Pull request merged**
