### PR TITLE
Clarify the transmission definition

### PR DESCRIPTION
**Pull request by tomflexcompute**
- Clarify the transmission definition in the Y branch notebook. 

- Modify the grid resolution in strip-to-slot converter so flux<1.

@alec-flexcompute feel free to point out anything else related to this PR.

### CODE REVIEW

**Comment by alec-flexcompute** [comment]
There's another instance in the 1x4 MMI power splitter

**Comment by alec-flexcompute** [comment]
There's also an instance in "Parametrized level-set optimization of a Y-branch"

**Comment by alec-flexcompute** [comment]
Otherwise I think that's all cases. Thanks Tom!

**Comment by tomflexcompute** [comment]
Ok thanks. The adjoint notebook is a bit hard to rerun and there is also a comment in the markdown about why there is a multiply of 2 so I'll leave that as it is for now.

**Pull request merged**
