### PR TITLE
prefab fab aware invdes notebook

### PR DESCRIPTION
**Pull request by tylerflex**
@Dusandinho 

Introduces prefab-flex compute colab 2.0. This time we optimize the WDM but with pre-fab prediction built into the optimization loop, so we end up simulating "real" devices. The final results show that the design is robust to fabrication variation compared to the one without any prefab in the loop. This is part of a concept called "FAID" or "Fabrication Aware Inverse Design"

### CODE REVIEW

**Review by e-g-melo — APPROVED** [review]
Hi @tylerflex! The results are very exciting!

I have only a few minor comments and typos:
1. Here, "which has n=4 output waveguides", it seems `n` is a variable, but it is not present on the code. It is not critical, but maybe you could explicitly define it as the number of channel wavelengths. 
2. Another cosmetic comment regards the use of "Static Simulation". In some notebooks we have "Base Simulation" and other ones use "Static Components". Maybe we should unify these names.
3. "We'll use `tidy3d`'s `ModeSolver`" -> "We'll use `Tidy3D`'s `ModeSolver`"
4. In [11], the chart legends overlap the curves. It is not possible to visualize the modes.
5. It seems something is missing here "number of pixels in x and y staticd on our design region resolution"
6. "Our objective whenn looking" -> "Our objective when looking"
7. "which we will feed to the optimizer.th" -> "which we will feed to the optimizer."

**Comment by tylerflex** [comment]
Thanks @e-g-melo , made all changes, and went with "Base simulation" for now. I agree we should be consistent. I have plans to standardize all of the notebooks, already started in #175

**Review by tomflexcompute — APPROVED** [review]
Very good demo. If similar processes can be done for foundry fab that would be a great pusher for industry adaptation of inverse design. 

When external libraries are needed, I think we typically comment out the `pip install` part so it can cut down the length of the page a bit.

The capitalization of the headers is a bit inconsistent. Could you double check?

A few typos in addition to Emerson's comment:

1. "the fabrication-predicted transmission spectra gets distorted" -> "the fabrication-predicted transmission spectra **get** distorted".
2. "input light of different wavelengths get directed" -> "input light of different wavelengths **gets** directed".
3. "on an SiO2 substrate" -> "on **a** SiO2 substrate".
4. "components that dont change" -> "components that **don't** change".
5. "specificiation" -> "specification".
6. "supressed" -> "suppressed".

Do you need me to add a schematic and metadata to the notebook?

**Comment by tylerflex** [comment]
thanks @tomflexcompute , I just made all changes. If you could add the metadadta and schematic if you get to it, that would be great. appreciate it

**Comment by tomflexcompute** [comment]
> thanks @tomflexcompute , I just made all changes. If you could add the metadadta and schematic if you get to it, that would be great. appreciate it

No problem will get to it either later today or early tomorrow.

**Comment by tomflexcompute** [comment]
@tylerflex feel free to check the image and metadata that were just added.

**Comment by tylerflex** [comment]
looks great, thanks tom!

**Review by yaugenst-flex — APPROVED** [review]
Looks super nice, don't have anything to add to the previous reviews. Thanks a lot!

**Pull request merged**
