### PR TITLE
update light extractor notebook

### PR DESCRIPTION
**Pull request by yaugenst-flex**
Reran the light extractor notebook because of 2.7.7 changes, also modified a few things:

 - Learning rate: 0.2 -> 0.1
 - Iterations: 100 -> 70
 - Added diagonal symmetry via `(x + x.T) / 2`
 - Exponential instead of linear beta schedule, with `beta_max = 150`
 - Use `smooth_min` with default `tau`

### CODE REVIEW

**Review by tomflexcompute — APPROVED** [review]
Thank @yaugenst-flex for updating the notebook. Looks great!

**Comment by tomflexcompute** [comment]
Btw you were using develop branch to run the notebook right?

**Comment by yaugenst-flex** [comment]
I was actually running from [this](https://github.com/flexcompute/tidy3d/pull/2082) branch, so we should hold off on merging this for a bit.

**Comment by fyc2646** [comment]
Sounds good.

**Comment by tylerflex** [comment]
would either @yaugenst-flex or @tomflexcompute mind fixing the merge conflict so we can merge this? The frontend PR fix has been merged into `develop`

**Comment by tomflexcompute** [comment]
hmm not sure why there is conflict. This branch was created from develop and these two files are unchanged in develop since then.

**Comment by yaugenst-flex** [comment]
should be ok now @tomflexcompute @tylerflex

**Pull request merged**
