### PR TITLE
A few changes

### PR DESCRIPTION
**Pull request by tomflexcompute**
- Added the missing time modulation tutorial notebook to medium.rst.
- Removed the structural color notebook from parameter_sweep.rst. Instead, added a link to this notebook in Design.ipynb
- Removed the metadata folder and the children files as they are not really used moving forward.

I was looking for the time modulation notebook and Just noticed that it is actually missing in the docs. @daquinteroflex not sure when the missing occurred but do you think the time modulation notebook was missing from the medium.rst during the repo migration? Would it be possible to check if all other notebooks are included in the rst files?

### CODE REVIEW

**Comment by daquinteroflex** [comment]
Whoops, I actually remember fixing this missing notebook explicitly, but maybe it was in another branch that didn't get merged.

Yes, I will do a full check, thanks for catching this!

**Review by e-g-melo — APPROVED** [review]
Thanks @tomflexcompute!

**Comment by tomflexcompute** [comment]
> Whoops, I actually remember fixing this missing notebook explicitly, but maybe it was in another branch that didn't get merged.
> 
> Yes, I will do a full check, thanks for catching this!

Thanks @daquinteroflex !

**Comment by daquinteroflex** [comment]
I did find two more that I have now fixed, going to merge this into develop to update the submodule state

**Review by daquinteroflex — APPROVED** [review]

**Comment by tomflexcompute** [comment]
Thanks @daquinteroflex !

**Comment by daquinteroflex** [comment]
It's live btw! https://docs.flexcompute.com/projects/tidy3d/en/latest/notebooks/TimeModulationTutorial.html

**Comment by tomflexcompute** [comment]
Great. Thanks @daquinteroflex

**Pull request merged**
