### PR TITLE
Fixed the dB scale

### PR DESCRIPTION
**Pull request by tomflexcompute**
In the overlap calculation, for some reason that I don't remember, I used 20*log10(overlap) to plot the overlap in dB scale. However the overlap itself should give power already so it should be 10*log10() instead?

### CODE REVIEW

**Review by momchil-flex — APPROVED** [review]
I think this makes sense, yeah.

**Review by e-g-melo — APPROVED** [review]

**Comment by tomflexcompute** [comment]
Actually after a second thought, I'm more confused. The `outer_dot` should give the amplitude so to calculate dB it should be `20*log10()`?

**Comment by momchil-flex** [comment]
Sorry. Yes, not sure why I didn't catch this before. The `dot` should be amplitude indeed.

**Comment by tomflexcompute** [comment]
Ok yeah that should be the case. Let me revert the revert the change earlier.

**Pull request merged**
