### PR TITLE
Tutorial on unstructured data

### PR DESCRIPTION
**Pull request by dbochkov-flexcompute**
long overdue tutorial on unstructured data

### CODE REVIEW

**Review by tomflexcompute — APPROVED** [review]
Thanks @dbochkov-flexcompute . Some minor comments:

"tetrahendron" -> "tetrahedron"
" a simple instances" -> " a simple instance"
"with many point" -> "with many points"
"operations extends data" -> "operations extend data"
"can be directly immediately using function .plot()." -> "can be directly visualized using function .plot()"?

Could you update `misc/import_file_mapping.json` since you have a file import?

**Review by e-g-melo — APPROVED** [review]
Hi @dbochkov-flexcompute! Thanks for this tutorial. It is very useful!

I will only suggest you include links to the existing heat examples and tutorials.

Emerson

**Comment by marc-flex** [comment]
This is awesome and very useful for me too :)

Only one thing:
- Links to the structures (e.g., [TriangularGridDataset](https://docs.flexcompute.com/projects/tidy3d/en/latest/api/_autosummary/tidy3d.TriangularGridDataset.html)) in the "Basics" cell don't work for me (I get 404 error)

**Review by marc-flex — APPROVED** [review]

**Comment by dbochkov-flexcompute** [comment]
Thanks for all the comments! All of them addressed now

> Only one thing:
> 
> * Links to the structures (e.g., [TriangularGridDataset](https://docs.flexcompute.com/projects/tidy3d/en/latest/api/_autosummary/tidy3d.TriangularGridDataset.html)) in the "Basics" cell don't work for me (I get 404 error)

After we build documentation for 2.7.0 this should be resolved https://github.com/flexcompute/tidy3d/pull/1571

**Pull request merged**
