### PR TITLE
use metrics in topology waveguide bend

### PR DESCRIPTION
**Pull request by tylerflex**

### CODE REVIEW

**Comment by tomflexcompute** [comment]
@tylerflex I pushed the updates in the other PR to your branch. The last cell still errors for me so please rerun it before merging if you can.

**Comment by tylerflex** [comment]
Thanks @tomflexcompute , this uncovered a small bug that we'll fix in another PR. Will re-run and merge this once it's done.

**Review by yaugenst-flex — APPROVED** [review]
Looks good! Note you _can_ use `f=freq0` (scalar) if you want.

**Comment by tylerflex** [comment]
I tried but it failed (develop branch)

**Pull request merged**
