### PR TITLE
Fix PIN MZI figure

### PR DESCRIPTION
**Pull request by dbochkov-flexcompute**

### CODE REVIEW

**Comment by tomflexcompute** [comment]
Thanks @dbochkov-flexcompute . I couldn't see the notebook diff for some reason. What did you change? Was there a typo?

**Comment by dbochkov-flexcompute** [comment]
@tomflexcompute turned out to be just a wrong filename (mzi_modulator.png -> MZI_modulator.png)

**Review by tomflexcompute — APPROVED** [review]
Thanks. Indeed that's the case. I modified the metadata as well for this so that when the website is built, it will grab the correct thumbnail image too. Ready to be merged.

**Comment by dbochkov-flexcompute** [comment]
@tomflexcompute thanks!

**Pull request merged**
