### PR TITLE
Added integrated Vivaldi antenna example

### PR DESCRIPTION
**Pull request by tomflexcompute**
This notebook demonstrates an integrated Vivaldi antenna. It's a bit long so feel free to take your time in the review. 

@QimingFlex feel free to take a look too if you are interested. We can update it to use the new directivity monitor once it's released.

### CODE REVIEW

**Review by alec-flexcompute — APPROVED** [review]
Excellent notebook @tomflexcompute! This is laid out and explained very well. I only have a couple suggestions:
1. When you mention staircasing, maybe hyperlink in this word to an explanation of staircasing
2. Above cell 16, change "can not" to "cannot" :)
3. _(light suggestion)_ When creating your FDTD validation simulation, maybe plot the simulation to show where the monitors are?
4. Above cell 27, maybe briefly explain what phi = 0 means in this case?

**Comment by tomflexcompute** [comment]
> Excellent notebook @tomflexcompute! This is laid out and explained very well. I only have a couple suggestions:
> 
> 1. When you mention staircasing, maybe hyperlink in this word to an explanation of staircasing
> 2. Above cell 16, change "can not" to "cannot" :)
> 3. _(light suggestion)_ When creating your FDTD validation simulation, maybe plot the simulation to show where the monitors are?
> 4. Above cell 27, maybe briefly explain what phi = 0 means in this case?

Thanks Alec. All are great suggestions. I'll wait for others' comments and make a revision together.

**Comment by FilipeFcp** [comment]
Really cool notebook, @tomflexcompute. There is not much to add to Alec's suggestions, so I will make some really minor comments.

1. Maybe mention that the effective length​ relation comes from normal mode analysis.

2. Maybe discuss a bit more about why you chose a finer mesh instead of an override mesh region.

3. Maybe explicitly state that PML would cause divergence due to dispersive materials.

**Comment by QimingFlex** [comment]
@tomflexcompute I really enjoyed reading the notebook and don't have any comments to add. We can definitely use the DirectivityMonitor to get the directivity and axial ratio in the next version. Also, I noticed you used a dense mesh of lambda_min/50. Hopefully, this can be alleviated once we have the corner detection feature in the future!

**Review by QimingFlex — APPROVED** [review]

**Review by e-g-melo — APPROVED** [review]
Hi @tomflexcompute! This is a very exciting new example. Congrats!

The list of features you have included in the introduction is very nice. It helps users to easily understand what they can learn within the notebook. I would suggest you include the subpixel volumetric averaging as an additional item in that list.

Best,
Emerson

**Review by FilipeFcp — APPROVED** [review]

**Comment by tomflexcompute** [comment]
Thanks everyone for the great feedback! Modifications have been implemented.

**Pull request merged**
