### PR TITLE
add apodized coupler example for autograd

### PR DESCRIPTION
**Pull request by tylerflex**

### CODE REVIEW

**Review by tomflexcompute — COMMENTED** [review]
Looks very good @tylerflex . Just a few small things:

- In the comment above cell[6], the minimal feature size is above 85 nm. 

- In the comment above cell[15], "functio" -> "function"

- Add plt.show() on the last figure to get out of the text output.

Currently metadata is missing. Do you want me to add it?

**Comment by tylerflex** [comment]
thanks tom, apparently I have trouble spelling "function" in every notebook..

Could you add the metadata after I give this another run through and a commit? I'll let you know,  thanks!

**Comment by tomflexcompute** [comment]
Yes of course! Take your time.

**Comment by tylerflex** [comment]
done, just pushed. could you add the metadata and make a new commit? and then I'll just wrap everything up and get this published

**Review by tomflexcompute — APPROVED** [review]
Thanks @tylerflex . Just added the metadata and pushed a commit. It turns out the waveguide bend notebook is missing a metadata field too so just added it in this commit as well. Everything looks good to go.

**Pull request merged**
